config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers:{    
     registrations: "users/registrations"   
  }
  root "gachas#index"
  resources :gachas, only: [:index, :new, :create, :show, :update, :edit]
  post  "/gachas/edit" ,to: "gachas#edit"
  resources :users, only: [:edit, :update]
  get  "/gachas/form/:id" ,to: "gachas#form",as: "form"
  post  "/gachas/result/:id" ,to: "gachas#result",as: "result"
  get  "/gachas/result/:id" ,to: "gachas#index"
  
  get '404', to: 'application#render_404'
  get '422', to: 'application#render_422'
  get '500', to: 'application#render_500'
  
end

app/controllers/gachas_controller.rb
class GachasController < ApplicationController
  before_action :form_params, only:[:show, :edit, :update, :form, :new, :result]
  before_action :find_params, only:[:edit, :update]
  def index
    @rarity = Rarity.order(updated_at: :desc).where(user_id:current_user).limit(1)
  end

  def show
    @selects = Rarity.order(updated_at: :desc).where(user_id:current_user).limit(5).offset(1)
    @button = Rarity.order(updated_at: :desc).where(user_id:current_user).limit(1)
  end

  def edit
    @selects = Rarity.find(@rarity.id)
  end

  def update
    @selects = Rarity.order(updated_at: :desc).where(user_id:current_user).limit(5)
    @rarity.touch
    redirect_to root_path, notice: 'ガチャ情報を変更しました'
  end
  
  def form
    @rarity = Rarity.order(updated_at: :desc).find_by(user_id:current_user)
    if @rarity.present?
      if @rarity.user_id == current_user.id
        session[:ref] = nil
      else
        redirect_to root_path, alert:"ガチャ情報を入力してください"
      end
    else
      redirect_to root_path, alert:"ガチャ情報を入力してください"
    end
  end

  def new
    @rarity = Rarity.new
  end

  def create
    @rarity = Rarity.new(rarity_params)
    if @rarity.price <= 0
      flash.now[:alert] = "回すガチャの金額は0よりも大きい値を入力してください"
      render :new 
    elsif @rarity.ssr < 0 || @rarity.sr < 0 || @rarity.r < 0 
      flash.now[:alert] = "排出率を0%より小さくしないでください"
      render :new 
    elsif @rarity.picup_ssr < 0 || @rarity.picup_sr < 0 || @rarity.picup_r < 0 
      flash.now[:alert] = "欲しいキャラの確率を0%より小さくしないでください"
      render :new 
    elsif @rarity.price >= 100000
      flash.now[:alert] = "回すガチャの金額100,000円よりも小さい値を入力してください"
      render :new 
    elsif (@rarity.ssr + @rarity.sr + @rarity.r).round(3) != 100
      flash.now[:alert] = "回すガチャの排出率の合計値を100%にしてください"
      render :new
    elsif @rarity.ssr < @rarity.picup_ssr || @rarity.sr < @rarity.picup_sr || @rarity.r < @rarity.picup_r
      flash.now[:alert] = "欲しいキャラの排出率が回すガチャより大きいです"
      render :new 
    else
      @rarity.save
      redirect_to root_path, notice: 'ガチャ情報が保存されました'
    end
  end

  def result
    if @form == 4
      probability_params()
    end
    @rarity = Rarity.order(updated_at: :desc).find_by(user_id:current_user)
    if @form == 1
      if params[:times].to_i <= 0
        flash.now[:alert] ="0回以下の値を入力しないでください"
        return render :form
      end
    elsif @form == 2
      if params[:times].to_i < @rarity.price
        flash.now[:alert] ="設定金額（#{@rarity.price}円）以上の値でないとガチャを回せません"
        return render :form
      end
    elsif @form == 3
      if params[:times].to_i == 0 && params[:times1].to_i == 0 && params[:times2].to_i== 0
        flash.now[:alert] ="欲しいキャラクターの割合を全て0%にしないでください"
        return render :form
      elsif params[:times].to_i < 0 || params[:times1].to_i < 0 || params[:times2].to_i < 0
        flash.now[:alert] = "0%未満の値を入力しないでください"
        return render :form
      end
    end
    if @form == 3
      @val = params.require(:times)
      @val2 = params.require(:times1)
      @val3 = params.require(:times2)
      respond_to do |format|
        format.html
        format.json
      end
    elsif @form == 1 || @form == 2
      @val = params.require(:times)
      respond_to do |format|
        format.html
        format.json
      end
    end
    if request.path_info != session[:ref]
      session[:ref] = request.path_info
      if params[:times] == "" || nil 
        redirect_to form_path
      else
        @result_form = params['id'].to_i
      end
    else
      redirect_to root_path, alert:"ガチャ結果画面で再読み込みをしないでください"
      session[:ref] = nil
    end
  end

  private
  def rarity_params
    params.require(:rarity).permit(:ssr, :sr, :r, :picup_ssr, :picup_sr, :picup_r, :price).merge(user_id: current_user.id)
  end

  def form_params
    @form = params['id'].to_i
  end

  def find_params
    @rarity = Rarity.find(params[:id])
  end

  def probability_params
    i = 0
    @count = []                 #当たった数の配列
    @count_times = 0
    probability_next = []       #確率の配列
    params[:times].length.times do |times|
      @count.push(0)
    end
    @probability = 0
    params[:probability].length.times do |times|
      @probability += (params[:probability][i].to_f)
      probability_next.push(@probability)
      i += 1
    end
    if probability_next.last > 100
      redirect_to form_path ,alert:"確率の合計が100%を超えています。"
    elsif params[:times][1].to_i < 0
      redirect_to form_path ,alert:"0以下の値を入力しないでください"
    else
      @times = params[:times]
      judge = true
      i = 0
      while judge do
        probability = BigDecimal((rand(0.0..100.0)).to_s).to_f
        @count_times += 1
        probability_next.each_with_index do|probability1, j|
          if probability <= probability_next[j]
            @count[j] += 1
            break
          end
        end
        judge = false
        @times.each_with_index do |times, k|
          if @times[k].to_i > @count[k]
            judge = true
          end
        end
      end
    end
  end
end

app/views/gachas/_footer.html.haml
-if @result_form == 1      
  =link_to "回数入力に戻る", form_path, class:"Editlink"
  %br
  =link_to "トップに戻る",root_path,class:"Editlink" 
  %br
  =link_to "GachaSimulator",root_path,class:"Editlink"
-elsif @result_form == 2     
  =link_to "金額入力に戻る", form_path, class:"Editlink"
  %br
  =link_to "トップに戻る",root_path,class:"Editlink" 
  %br
  =link_to "GachaSimulator",root_path,class:"Editlink"
-elsif @result_form == 3 ||  @result_form == 4   
  =link_to "入力に戻る", form_path, class:"Editlink"
  %br
  =link_to "トップに戻る",root_path,class:"Editlink" 
  %br
  =link_to "GachaSimulator",root_path,class:"Editlink"
-elsif @form.present?
  =link_to "トップに戻る",root_path,class:"Editlink" 
  %br
  =link_to "GachaSimulator",root_path,class:"Editlink"
-else
  =link_to "GachaSimulator",root_path,class:"Editlink"

app/views/gachas/_header.html.haml
-if user_signed_in?
  .gacha_main__header
    .gacha_main__header_title
      = link_to "GachaSimulator", root_path, class:"title"
      .gacha_main__btn 
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
        = link_to "アカウント情報編集", edit_user_path(current_user) ,class: 'btn'
    .gacha_main__header_user
      name: 
      = current_user.name
-else
  .gacha_main__header
    .gacha_main__header_title
      = link_to "GachaSimulator", "#", class:"title"

app/views/gachas/create.html.haml
.result_form
  .result_form__header
    GachaSimulator2020
  .result_form__1
    %input.data{:class=>"data", :type=>"hidden" , :name=>"data", :value=>@val}
  .result_form__2
    result<br>
  :javascript
    $(function(){
      var val=$(".data").val();
          ssr = 0
          sr = 0
          r = 0
        for (let time = 0; time < val; time++) {
          rarity = Math.ceil( Math.random()*100 );  //1~100の範囲でランダムに数字を取得
            if (rarity <= 3){                       //確率３％
                ssr = ssr + 1
            }else if (rarity <= 18){                //確率１５％
                sr = sr + 1
            }else{                                  //確率８２％
                r = r + 1
            }
        }
        //ガチャ結果の表示
        $('.result_form__2').append("SSR:" + ssr + "<br>\n"); 
        $('.result_form__2').append("SR:" + sr + "<br>\n"); 
        $('.result_form__2').append("R:" + r + "<br>\n"); 

        $('.result_form__2').append("確率" + "<br>\n"); 
        //ガチャ結果の確率の計算
        SSR =  Math.round((ssr / val * 100))
        SR =  Math.round((sr / val * 100))
        R =  Math.round((r / val * 100))

        //ガチャ結果の確率の表示
        $('.result_form__2').append("SSR:" + SSR+ "%<br>\n"); 
        $('.result_form__2').append("SR:" + SR+ "%<br>\n"); 
        $('.result_form__2').append("R:" + R+ "%<br>\n"); 

      })    

  .result_form__back
    %a{href: 'http://localhost:3000/gachas/new'} ガチャ回数入力に戻る<br>
    %a{href: 'http://localhost:3000'} トップに戻る
  .result_form__footer
    GachaSimulator2020

app/views/gachas/edit.html.haml
.gacha_main
  = render "header"
  .gacha_main__edit
    下記のガチャ情報を保存しますか？
    .gacha_main__edit_table
      %table{:border => "5",class:"select"}
        %tr{bgcolor:"#40E0D0"}
          %th SSR
          %th SR
          %th R
          %th 欲しいSSR
          %th 欲しいSR
          %th 欲しいR
          %th 金額
        %tr
          %td 
            =@selects.ssr
            \%
          %td 
            =@selects.sr
            \%
          %td
            =@selects.r
            \%
          %td
            =@selects.picup_ssr
            \%
          %td
            =@selects.picup_sr
            \%
          %td
            =@selects.picup_r  
            \% 
          %td   
            =@selects.price
            円
    = form_with(url:gacha_path(@selects.id),model: @rarity, method: :patch, local: true) do |f|
      =link_to "いいえ",gacha_path(current_user), class:'btn-select'
      =f.submit "はい", class:'btn-submit'
  .result_form__footer
    =render "footer"

app/views/gachas/form.html.haml
.gacha_main
  =render "header"
  -if @form == 1
    .gacha_main__form
      =form_with(url: result_path(1), class: "Form", id: "form", local: true) do |f|
        %p 回したい数を入力してください
        =f.number_field :time, id: "time", class: 'text',name: "times", step:"1", max:"10000000", onsubmit:"result();",placeholder:"回数",required: true
        回
        =f.submit'ガチャる', class:'send-btn'
  -elsif @form == 2
    .gacha_main__form
      =form_with(url: result_path(2), class: "Form", id: "form", local: true) do |f|
        %p ガチャに使用する金額を入力してください
        =f.number_field :time, id: "time", class: 'text',name: "times",max:"10000000", onsubmit:"charges();",placeholder:"金額",required: true
        円
        =f.submit'ガチャる', class:'send-btn'
  -elsif @form == 3
    .gacha_main__form
      =form_with(url: result_path(3), class: "Form", id: "form", local: true) do |f|
        %p 欲しいキャラの数を入力してください
        SSR:
        -if @rarity.picup_ssr == 0
          =f.number_field :ssr ,class:'rate1',name: "times", step:"1",value:"0", onsubmit:"times();", readonly:"readonly"
        -else
          =f.number_field :ssr ,class:'rate',name: "times",max:"1000", step:"1", required: true, placeholder: "0", onsubmit:"times();"
        体
        SR:
        -if @rarity.picup_sr == 0
          =f.number_field :sr,class:'rate1',name: "times1", step:"1", value:"0", onsubmit:"times();", readonly:"readonly"
        - else
          =f.number_field :sr,class:'rate',name: "times1",max:"1000", step:"1", required: true, placeholder: "0", onsubmit:"times();"
        体
        R:
        -if @rarity.picup_r == 0
          =f.number_field :r ,class:'rate1',name: "times2", step:"1",value:"0", onsubmit:"times();", readonly:"readonly"
        -else
          =f.number_field :r ,class:'rate',name: "times2",max:"1000", step:"1", required: true, placeholder: "0", onsubmit:"times();"
        体
        =f.submit'ガチャる', class:'send-btn'
  -else
    .gacha_main__form_special
      =form_with(url: result_path(4), class: "Form", id: "form", local: true) do |f|
        %div.content 欲しいキャラが何体かとその確率を入力してください
        .form_special_1
          %button{type: "button",class:'Contents__btn', id:"existForm"}
            = icon('far', 'minus-square')
          %button{type: "button",class:'Contents__btn', id:"addForm"}
            = icon('far', 'plus-square')
          1体目  欲しい数:
          =f.number_field :time ,name: "times[]",class: "rate", max:"1000",onsubmit:"special();",placeholder:"0",required: true
          体
          確率:
          =f.number_field :time1,name: "probability[]",class: "rate", max:"1000",onsubmit:"special();",placeholder:"0",required: true, step:"0.0001"
          \%
        .form_special_4

        .form_special_5
          =f.submit'ガチャる', class:'send-btn'
        
  %input.SSR{:type=>"hidden" , :name=>"SSR", :value=>@rarity.ssr}
  %input.SR{:type=>"hidden" , :name=>"data2", :value=>@rarity.sr}
  %input.R{:type=>"hidden" , :name=>"data3", :value=>@rarity.r}
  %input.picup_ssr{:type=>"hidden" , :name=>"data4", :value=>@rarity.picup_ssr}
  %input.picup_sr{:type=>"hidden" , :name=>"data5", :value=>@rarity.picup_sr}
  %input.picup_r{:type=>"hidden" , :name=>"data6", :value=>@rarity.picup_r}
  %input.arr_json{:name => "arr_json", :type => "hidden", :value => "@arr_json"}


  .gacha_main__rate
    -if @form == 3
      %button{type: "button",class:'btn btn--orange btn--radius',onclick:'pic()'}
        欲しいキャラの割合<br>
    -elsif @form == 1 || @form == 2
      %button{type: "button",class:'btn btn--orange btn--radius',onclick:'rate()'}
        提供割合<br>
  .gacha_main__footer
    =render "footer"

app/views/gachas/index.html.haml
-# %canvas(id="projector")
-#   Your browser does not support the Canvas element.
.gacha_main
  = render "header"
  .gacha_main__aaa
    .gacha_main__form_index
      %p ようこそ!ガチャシミュレーションへ
      %p 回すガチャの情報を入力してください
      .gacha_main__form_index_information
        = link_to  new_gacha_path,class:"Editlink_index" do
          情報入力
      %p
        たくさん回したい方は
        %span.gacha_main__underline
        = link_to form_path(1),class:"Editlink_index" do
          気にせずガチャ
      %p
        金額に応じて回したい方は
        %span.gacha_main__underline
        = link_to form_path(2) ,class:"Editlink_index" do
          課金額ガチャ
      %p
        何回引けばいいか知りたい方は
        %span.gacha_main__underline
        = link_to form_path(3) ,class:"Editlink_index" do
          出るまでガチャ
      %p
        欲しいキャラが多い方は
        %span.gacha_main__underline
        = link_to form_path(4) ,class:"Editlink_index" do
          出るまでガチャver.2.0
    .gacha_main__information
      %p
        現在の情報
      .gacha_main__probability
        -@rarity.each do |select|
          %p
            排出率
          .ssr
            %p
              SSR:
              =select.ssr
              \%
          .sr
            %p
              SR:
              =select.sr
              \%
          .r
            %p
              R
              =select.r
              \%
      .gacha_main__need
        -@rarity.each do |select|
          %P
            欲しいキャラの排出率
          .ssr
            %p
              SSR:
              =select.picup_ssr
              \%
          .sr
            %p
              SR:
              =select.picup_sr
              \%
          .r
            %p
              R:
              =select.picup_r  
              \%
      .gacha_main__price
        -@rarity.each do |select|
          %p
            ガチャ一回あたりの金額
          .price
            =select.price
            円
      = link_to "過去の情報を取得", gacha_path(current_user), class:"btn"
  .gacha_main__footer
    =render "footer"

app/views/gachas/new.html.haml
.gacha_main
  = render "header"
  .gacha_main__form_rate
    =form_with(url: gachas_path, model: @rarity, class: "Form", id: "form", local: true) do |f|
      %p 回すガチャの排出率を入力してください
      %p.example (例：SSR : 6%  SR : 24%  R : 70%)
      SSR:
      =f.number_field :ssr ,class:'rate', step:"0.1", required: true, placeholder: "0"
      \%
      SR:
      =f.number_field :sr,class:'rate', step:"0.1", required: true, placeholder: "0"
      \%
      R:
      =f.number_field :r ,class:'rate', step:"0.1", required: true, placeholder: "0"
      \%
      <br><br>
      %p 欲しいキャラ1体あたりの排出率を入力してください
      %p.example (例：SSR : 2%  SR : 3%  R : 10%)
      SSR:
      =f.number_field :picup_ssr,class:'rate', step:"0.0001", required: true, placeholder: "0"
      \%
      SR:
      =f.number_field :picup_sr,class:'rate', step:"0.0001", required: true, placeholder: "0"
      \%
      R:
      =f.number_field :picup_r,class:'rate', step:"0.0001", required: true, placeholder: "0"
      \%
      <br><br>
      %p 引くガチャ1回の金額を入力してください
      金額:
      =f.number_field :price, class:'rate_price', required: true, placeholder: "0"
      円
      <br>
      = link_to "過去の情報を取得", gacha_path(current_user), class:"select-btn"
      = f.submit 'クリア', type: :reset, class:"reset"
      = f.submit'決定', class:'send-rate-btn'
  .gacha_main__footer
    =render "footer"

app/views/gachas/result.html.haml
.result_form
  .result
  =render "header"
  -if @result_form == 1
    .result_form__1
      %input.data{:class=>"data", :type=>"hidden" , :name=>"data", :value=>@val}
      %input.SSR{:type=>"hidden" , :name=>"SSR", :value=>@rarity.ssr}
      %input.data{:class=>"SR", :type=>"hidden" , :name=>"data2", :value=>@rarity.sr}
      %input.data{:class=>"R", :type=>"hidden" , :name=>"data3", :value=>@rarity.r}
    .result_form__2
    .result_form__footer
      =render "footer"
  -elsif @result_form == 2
    .result_form__1
      %input.data{:class=>"data", :type=>"hidden" , :name=>"data", :value=>@val}
      %input.SSR{:type=>"hidden" , :name=>"SSR", :value=>@rarity.ssr}
      %input.SR{:type=>"hidden" , :name=>"data2", :value=>@rarity.sr}
      %input.R{:type=>"hidden" , :name=>"data3", :value=>@rarity.r}
      %input.picup_ssr{:type=>"hidden" , :name=>"data4", :value=>@rarity.picup_ssr}
      %input.picup_sr{:type=>"hidden" , :name=>"data5", :value=>@rarity.picup_sr}
      %input.picup_r{:type=>"hidden" , :name=>"data6", :value=>@rarity.picup_r}
      %input.price{:type=>"hidden" , :name=>"data7", :value=>@rarity.price}
    .result_form__3
    .result_form__footer
      =render "footer"
  -elsif @result_form == 3
    .result_form__1
      %input.data_ssr{ :type=>"hidden" , :name=>"data", :value=>@val}
      %input.data_sr{:type=>"hidden" , :name=>"data8", :value=>@val2}
      %input.data_r{:type=>"hidden" , :name=>"data9", :value=>@val3}
      %input.SSR{:type=>"hidden" , :name=>"SSR", :value=>@rarity.ssr}
      %input.SR{:type=>"hidden" , :name=>"data2", :value=>@rarity.sr}
      %input.R{:type=>"hidden" , :name=>"data3", :value=>@rarity.r}
      %input.picup_ssr{:type=>"hidden" , :name=>"data4", :value=>@rarity.picup_ssr}
      %input.picup_sr{:type=>"hidden" , :name=>"data5", :value=>@rarity.picup_sr}
      %input.picup_r{:type=>"hidden" , :name=>"data6", :value=>@rarity.picup_r}
      %input.price{:type=>"hidden" , :name=>"data7", :value=>@rarity.price}
    .result_form__4
    .result_form__footer
      =render "footer"
  -elsif @result_form == 4
    .result_form__5
      %p
        %span.result_font_SSR
          =@count_times
        回引くと全てのキャラが出ました
      -@count.each_with_index do|count, i|
        %p
          %span.font-large
            =i+1
          体目
          %span.result_font_SR
            =@count[i]
          体出ました

    .result_form__footer
      =render "footer"
.result_form_image
  = image_tag("result2.jpg", class:"image")

app/views/gachas/show.html.haml
.gacha_main
  = render "header"
  .gacha_main__title
    現在の情報
    .gacha_main__button
      -if @button.present?
        %table{:border => "5",class:"button"}
          %tr{bgcolor:"#40E0D0"}
            %th SSR
            %th SR
            %th R
            %th 欲しいSSR
            %th 欲しいSR
            %th 欲しいR
            %th 金額
          -@button.each do |select|
            %tr
              %td 
                =select.ssr
                \%
              %td 
                =select.sr
                \%
              %td
                =select.r
                \%
              %td
                =select.picup_ssr
                \%
              %td
                =select.picup_sr
                \%
              %td
                =select.picup_r  
                \% 
              %td   
                =select.price
                円
      -else 
        現在の情報はありません
  .gacha_main__past
    過去の情報一覧(最新５件)
    .gacha_main__select
      -if @selects.present?
        %table{border: "5" ,class:"select"}
          %tr{bgcolor:"#40E0D0"}
            %th.ssr
              SSR
            %th SR
            %th R
            %th 欲しいSSR
            %th 欲しいSR
            %th 欲しいR
            %th.price
              金額
            %th.select
              
          -@selects.each do |select|
            %tr
              %td 
                =select.ssr
                \%
              %td 
                =select.sr
                \%
              %td
                =select.r
                \%
              %td
                =select.picup_ssr
                \%
              %td
                =select.picup_sr
                \%
              %td
                =select.picup_r  
                \% 
              %td     
                =select.price
                円
              %td.select
                =link_to "選択", edit_gacha_path(select.id), class:"btn-select"
      -else
        過去に登録された情報はありません
        <br>
      =link_to "情報入力フォームに戻る", new_gacha_path, class:"btn-link"
  .result_form__footer
    =render "footer"